ads/urls.py
from django.urls import path
from .views import (AdList, MyAdList, AdDetailView, AdCreateView, AdEditView, AdDeleteView, OfferListView, OfferDeleteView)


urlpatterns = [
    path('', AdList.as_view(), name='ads_list'),
    path('my-ads', MyAdList.as_view(), name='my_ads'),
    path('<int:pk>', AdDetailView.as_view(), name='ad_detail'),
    path('create/', AdCreateView.as_view(), name='ad_create'),
    path('update/<int:pk>/', AdEditView.as_view(), name='ad_edit'),
    path('delete/<int:pk>/', AdDeleteView.as_view(), name='ad_delete'),
    path('offers', OfferListView.as_view(), name='offers'),
    path('offers/accept/<int:pk>', OfferListView.accept, name='offer_accept'),
    path('offers/delete/<int:pk>', OfferDeleteView.as_view(), name='offer_delete'),
]

billboard_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ads.urls')),
    path('users/', include('allauth.urls')),
    path('user/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


ads/models.py
from django.db import models
from django.urls import reverse
from .validators import validate_video_format

# Create your models here.

class Ad(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    category = models.CharField(
        max_length=2,
        choices=[
            ('TA', 'Танки'),
            ('HE', 'Хилы'),
            ('DD', 'ДД'),
            ('TO', 'Торговцы'),
            ('GI', 'Гилдмастеры'),
            ('KV', 'Квестгиверы'),
            ('KU', 'Кузнецы'),
            ('KO', 'Кожевники'),
            ('ZE', 'Зельевары'),
            ('MZ', 'Мастера заклинаний')
        ],
        default='TA'
    )
    posted = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    image1 = models.ImageField(upload_to='images/', null=True, blank=True)
    image2 = models.ImageField(upload_to='images/', null=True, blank=True)
    image3 = models.ImageField(upload_to='images/', null=True, blank=True)
    video = models.FileField(upload_to='videos/', null=True, blank=True,
                             validators=[validate_video_format])

    def __str__(self):
        return f'{self.title} ({self.posted.ctime()})'

    def get_absolute_url(self):
        return reverse('ad_detail', kwargs={'pk': self.pk})


class Offer(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    posted = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    is_accepted = models.BooleanField(default=False)

    def __str__(self):
        if len(self.text) < 50:
            snippet = self.text
        else:
            snippet = self.text[:50].rsplit(' ', 1)[0] + '...'

        return f'{snippet} ({self.posted.ctime()})'

ads/forms.py
from django import forms
from django.forms import ModelForm, HiddenInput
from .models import Ad, Offer


class AdForm(ModelForm):
    class Meta:
        model = Ad
        fields = ['author', 'title', 'category', 'content',
                  'image1', 'image2', 'image3', 'video']
        widgets = {
            'author': HiddenInput()
        }


class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = ['user', 'ad', 'text']
        labels = {'text': ''}
        widgets = {
            'user': HiddenInput(),
            'ad': HiddenInput(),
            'text': forms.Textarea(attrs={'placeholder': 'Напишите здесь Ваш отклик'})
        }

ads/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail

from .models import Ad, Offer
from .forms import AdForm, OfferForm
from .filters import OfferFilter

# Create your views here.


class AdList(LoginRequiredMixin, ListView):
    model = Ad
    template_name = 'ads/ad_list.html'
    context_object_name = 'ads'
    ordering = ['-posted']
    paginate_by = 10


class MyAdList(LoginRequiredMixin, ListView):
    model = Ad
    template_name = 'ads/ad_list.html'
    context_object_name = 'ads'
    ordering = ['-posted']

    def get_queryset(self):
        return Ad.objects.filter(author=self.request.user)


class AdDetailView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'ads/ad_detail.html'
    queryset = Ad.objects.all()
    form_class = OfferForm

    def get_success_url(self):
        return reverse_lazy('ad_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(AdDetailView, self).get_context_data(**kwargs)
        context['offers'] = Offer.objects.filter(ad=self.object)
        context['form'] = OfferForm(
            {'user': self.request.user, 'ad': self.object}
        )
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        send_mail(
            subject='На Ваше объявление откликнулись!',
            message=f'На Ваше объявление откликнулся пользователь {self.request.user}!',
            from_email=None,
            recipient_list=[self.object.author.email]
        )
        return super(AdDetailView, self).form_valid(form)


class AdCreateView(LoginRequiredMixin, CreateView):
    template_name = 'ads/ad_create.html'
    form_class = AdForm
    success_url = reverse_lazy('ads_list')

    def get_context_data(self, **kwargs):
        context = super(AdCreateView, self).get_context_data(**kwargs)
        context['form'] = AdForm(
            {'author': self.request.user}
        )
        return context


class AdEditView(LoginRequiredMixin, UpdateView):
    template_name = 'ads/ad_create.html'
    form_class = AdForm
    success_url = reverse_lazy('ads_list')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Ad.objects.get(pk=id)

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        ad = self.get_object()
        if not (ad.author == user or user.is_superuser):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class AdDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'ads/ad_delete.html'
    queryset = Ad.objects.all()
    success_url = reverse_lazy('ads_list')

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        ad = self.get_object()
        if not (ad.author == user or user.is_superuser):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class OfferListView(LoginRequiredMixin, ListView):
    model = Offer
    template_name = 'ads/offers.html'
    context_object_name = 'offers'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = OfferFilter(
            self.request.GET, queryset=self.get_queryset()
        )
        return context

    def get_queryset(self):
        context = Offer.objects.filter(ad__author=self.request.user)
        return context

    def accept(request, pk):
        offer = Offer.objects.get(pk=pk)
        offer.is_accepted = not offer.is_accepted
        offer.save()

        send_mail(
            subject='Ваш отклик принят!',
            message='Ваш отклик принят!',
            from_email=None,
            recipient_list=[offer.user.email]
        )

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class OfferDeleteView(LoginRequiredMixin, DeleteView):
    model = Offer
    success_url = reverse_lazy('offers')


templates/ads/ad_create.html
{% extends 'default.html' %}

{% block title %}
  Новое объявление
{% endblock title %}

{% block content %}
  <h1>Создание нового объявления:</h1>
  <form method="post" enctype="multipart/form-data">  
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      {{ field.errors }}
      {{ field.label_tag }}

      {% if field.label == 'Image1' or field.label == 'Image2' or field.label == 'Image3' or field.label == 'Video' %}
        <div>
          {{ field }}
        </div>
      {% else %}
        {{ field }}        
      {% endif %}
    {% endfor %}  
    <br>
    <input type="submit" value="Добавить объявление">
  </form>
{% endblock content %}

templates/ads/ad_delete.html
{% extends 'default.html' %}

{% block title %}
  Удаение объявления
{% endblock title %}

{% block content %}
  <br> 
  <h2>Вы уверены, что хотите удалить объявление?</h2>
  <br> 
  <p>- - -</p>
  <h4>{{ ad.title }}</h4>
  <h6>Автор: {{ ad.author }}</h6>
  <h6>Дата: {{ ad.posted }}</h6>
  <h5>{{ ad.content }}</h5>
  <p>- - -</p>

  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Удалить">
  </form>
{% endblock content %}

templates/ads/ad_detail.html
{% extends 'default.html' %}

{% block title %}
  {{ ad.title }}
{% endblock title %}

{% block content %}

  <h2>{{ ad.title }}</h2>
  <h6>Автор: {{ ad.author }}</h6>
  <h5>Дата: {{ ad.posted }}</h5>
  <h5>Категория: {{ ad.get_category_display }}</p>
  <h3>{{ ad.content }}</h3>

  <div class="ad-detail__media">
    {% if ad.image1 %}
      <a href="{{ ad.image1.url }}"><img src="{{ ad.image1.url }}" alt="{{ ad.image.url }}"></a>
    {% endif %}

    {% if ad.image2 %}
      <a href="{{ ad.image2.url }}"><img src="{{ ad.image2.url }}" alt="{{ ad.image.url }}"></a>
    {% endif %}

    {% if ad.image3 %}
      <a href="{{ ad.image3.url }}"><img src="{{ ad.image3.url }}" alt="{{ ad.image.url }}"></a>
    {% endif %}

    {% if ad.video %}  
      <video controls>
        <source src="{{ ad.video.url }}" type="video/mp4">
        <source src="{{ ad.video.url }}" type="video/webm">
        К сожалению, ваш браузер не поддерживает встроенные видео.
      </video>
    {% endif %}
  </div>

  <form action="{% url 'ad_detail' object.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br>
    <button type="submit">Отправить отклик</button>
  </form>

{% endblock content %}

templates/ads/ad_list.html
{% extends 'default.html' %}

{% load static %}

{% block title %}
  Мои объявления
{% endblock title %}

{% block content %}
  <div>
    {% for ad in ads %}
      <div>
        <a href="{% url 'ad_detail' ad.id %}">
          <h2>{{ ad.title }}</h2>
        </a>

        <h6>
          Автор: {{ ad.author }}
          {% if ad.author == request.user %}
            (Это Вы)
          {% endif %}
        </h6>
        <h7>Дата: {{ ad.posted }}</h7>
        <br>
        <h7>Категория объявления: {{ ad.get_category_display }}</h7>
        <p>- - -</p>
        <h4>{{ ad.content | truncatewords:50 }}</h4>
        <br>  
        
        <div>
          {% if ad.image1 or ad.image2 or ad.image3 %}
            <img src="{% static 'img/photo.png' %}" alt="" width=15 height=15>
          {% endif %}
          {% if ad.video %}
            <img src="{% static 'img/video.png' %}" alt="" width=15 height=15>
          {% endif %}
        </div>

          {% if ad.author == request.user %}
            <div>
              <p>- - -</p>
              <button> <a href="{% url 'ad_edit' ad.id %}">Редактировать объявление</a> </button> 
              <br><br>
              <button> <a href="{% url 'ad_delete' ad.id %}">Удалить объявление</a> </button> 
            </div>
          {% endif %}
          <br>  
      </div>
      <hr>
    {% empty %}
      <h2>Объявлений еще нет!</h2>
    {% endfor %}

  </div>
 

  {% if is_paginated %}
      <nav>
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li><a href="?page=1">First</a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}"><<<</a></li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <li class="pagination_active">{{ num }}</li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:3 %}
              <li><a href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">>>></a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock content %}

templates/ads/offers.html
{% extends 'default.html' %}
{% load static %}

{% block title %}
  Мои отклики
{% endblock title %}

{% block content %}
<h1>Мои отклики:</h1>
  <form method="GET">
    {{ filter.form }}
    <input type="submit" value="Поиск отклика">
  </form>
  <ul style="list-style-type:none;">
    {% for offer in filter.qs %}
      <li {% if offer.is_accepted %} style="background-color:lightgreen;"{% endif %}>
        <div>
          <h5>
            <span>
              {{ offer.user }} оставил отклик к объявлению: 
              <a href="{{ offer.ad.get_absolute_url }}">{{offer.ad.title | truncatechars:50 }}</a>
            </span>
            <br> <br> 
            {{ offer.text }}
          </h5>

        </div>
        <br>
        <a href="{% url 'offer_accept' offer.pk %}">
          {% if not offer.is_accepted %}
            <input type="submit" value="Принять отклик">
          {% else %}
            <input type="submit" value="Отменить отклик">
          {% endif %}
        </a>

        <form action="{% url 'offer_delete' offer.pk %}" method="post">
          {% csrf_token %}
          <button> Удалить объявление </button> 
        </form>
      </li><hr>
    {% endfor %}
  </ul>
{% endblock content %}